### ISSUE TITLE
MSON aligned parameter parser trips up when inline description contains round brackets

### ISSUE THREAD

**Issue by kylef** [apiaryio/snowcrash#345] opened 2015-08-12 20:31 UTC
When an inline description of an MSON aligned parameter is used that contains round brackets `()` the parser seems to trip up and says the whole block is unrecognised.

![screen shot 2015-08-12 at 21 28 28](https://cloud.githubusercontent.com/assets/44164/9235898/7fbed54e-4139-11e5-8985-2fd748763a4c.png)

### Problematic syntax

```apib
+ Parameters
    + query (string) - This is a (short) inline description
```

### Working alternatives

```apib
+ Parameters
    + query - This is a (short) inline description
```

```apib
+ Parameters
    + query (string)
        This is a (short) inline description
```

**Comment by pksunkara** [comment] 2015-08-12 20:33
Can you try the following:

```apib
+ Parameters
    + query: sample (string) - This is a (short) inline description
```

**Comment by kylef** [comment] 2015-08-12 20:34
That also works @pksunkara.

**Comment by pksunkara** [comment] 2015-08-12 20:36
@kylef The problem is that the default is old parameter style. Since the following parameter is also valid old style paramter, it will default to old style parameter and try to parse it which is giving the error.

```
+ query (string) - This is a (short) inline description
```

**Comment by kylef** [comment] 2015-08-12 20:43
> Since the following parameter is also valid old style parameter

But this isn't valid with the old syntax because it throws an error?

**Comment by pksunkara** [comment] 2015-08-12 20:44
Yes. So, we need to add the option of trying to parse with the other style if the recognised style throws error.

**Comment by pksunkara** [comment] 2016-02-09 14:55
Actually, the issue here is in trying to recognise the parameter syntax style. Instead of trying to match brackets, [this](https://github.com/apiaryio/snowcrash/blob/5dac8f1548806ddf2a25bafd47ba504218474ff6/src/ParameterParser.h#L518) line directly goes to the last closing bracket. And when the next non-empty character is not a description delimiter, the parameter doesn't get recognised as a whole.

**Closed** 2016-09-01 15:44 UTC
Labels: bug
